let default_decks = [{
    "title": "Northern Realms",
    "description": "Deck relying mostly on Tight Bonds units and Spies",
    "leader": "nr_foltest_lord",
    "faction": "realms",
    "cards": [
        ["spe_horn", 1],
        ["spe_decoy", 2],
        ["spe_scorch", 1],
        ["spe_clear", 1],
        ["spe_fog", 1],
        ["spe_rain", 1],
        ["ntr_ciri", 1],
        ["ntr_yennefer", 1],
        ["nr_ves", 1],
        ["ntr_geralt", 1],
        ["nr_natalis", 1],
        ["nr_vernon", 1],
        ["nr_stennis", 1],
        ["nr_keira", 1],
        ["nr_dijkstra", 1],
        ["nr_sheala", 1],
        ["nr_thaler", 1],
        ["ntr_triss", 1],
        ["nr_olgierd", 1],
        ["nr_crinfrid_1", 1],
        ["nr_crinfrid_2", 1],
        ["nr_crinfrid_3", 1],
        ["nr_villen", 1],
        ["nr_blue_stripes_1", 1],
        ["nr_blue_stripes_2", 1],
        ["nr_blue_stripes_3", 1],
        ["nr_poor_infantry_1", 1],
        ["nr_poor_infantry_2", 1],
        ["nr_poor_infantry_3", 1],
        ["nr_banner_nurse", 1],
        ["nr_catapult_1", 1],
        ["nr_catapult_2", 1],
        ["nr_ballista_1", 1],
        ["nr_ballista_2", 1],
        ["nr_kaedwen_siege_1", 1],
        ["nr_kaedwen_siege_2", 1],
    ]
},
{
    "title": "Northern Realms",
    "description": "",
    "leader": "nr_foltest_king",
    "faction": "realms",
    "cards": [
        ["spe_horn", 2],
        ["spe_decoy", 1],
        ["spe_scorch", 2],
        ["spe_clear", 1],
        ["spe_fog", 1],
        ["spe_rain", 2],
        ["ntr_ciri", 1],
        ["ntr_geralt", 1],
        ["nr_natalis", 1],
        ["nr_vernon", 1],
        ["nr_stennis", 1],
        ["nr_trebuchet", 1],
        ["nr_keira", 1],
        ["nr_dijkstra", 1],
        ["ntr_mysterious_elf", 1],
        ["nr_thaler", 1],
        ["nr_catapult_2", 1],
        ["nr_ballista_1", 1],
        ["ntr_triss", 1],
        ["nr_olgierd", 1],
        ["nr_ballista_1", 1],
        ["nr_ballista_2", 1],
        ["nr_kaedwen_siege_1", 1],
        ["nr_crinfrid_1", 1],
        ["nr_crinfrid_2", 1],
        ["nr_crinfrid_3", 1],
        ["nr_villen", 1],
        ["ntr_yennefer", 1],
        ["nr_ves", 1],
        ["nr_blue_stripes_1", 1],
        ["nr_blue_stripes_2", 1],
        ["nr_blue_stripes_3", 1],
        ["nr_poor_infantry_1", 1],
        ["nr_poor_infantry_2", 1],
        ["nr_poor_infantry_3", 1],
        ["nr_banner_nurse", 1]
    ]
},
{
    "title": "Northern Realms",
    "description": "",
    "leader": "nr_foltest_siegemaster",
    "faction": "realms",
    "cards": [
        ["spe_horn", 2],
        ["spe_decoy", 2],
        ["spe_scorch", 1],
        ["spe_clear", 1],
        ["spe_fog", 1],
        ["spe_rain", 1],
        ["ntr_ciri", 1],
        ["ntr_geralt", 1],
        ["nr_natalis", 1],
        ["nr_vernon", 1],
        ["nr_stennis", 1],
        ["ntr_mysterious_elf", 1],
        ["nr_dijkstra", 1],
        ["nr_sheala", 1],
        ["nr_thaler", 1],
        ["nr_ballista_1", 1],
        ["nr_ballista_2", 1],
        ["nr_zoltan", 1],
        ["ntr_triss", 1],
        ["nr_olgierd", 1],
        ["nr_crinfrid_1", 1],
        ["nr_crinfrid_2", 1],
        ["nr_crinfrid_3", 1],
        ["nr_villen", 1],
        ["nr_kaedwen_siege_1", 1],
        ["nr_kaedwen_siege_2", 1],
        ["nr_blue_stripes_1", 1],
        ["nr_blue_stripes_2", 1],
        ["nr_blue_stripes_3", 1],
        ["nr_poor_infantry_1", 1],
        ["nr_poor_infantry_2", 1],
        ["nr_poor_infantry_3", 1],
        ["nr_banner_nurse", 1]
    ]
},
{
    "title": "Northern Realms",
    "description": "",
    "leader": "nr_foltest_steelforged",
    "faction": "realms",
    "cards": [
        ["spe_horn", 1],
        ["spe_decoy", 2],
        ["spe_scorch", 1],
        ["spe_clear", 1],
        ["spe_fog", 1],
        ["spe_rain", 1],
        ["ntr_ciri", 1],
        ["ntr_geralt", 1],
        ["nr_natalis", 1],
        ["nr_vernon", 1],
        ["nr_stennis", 1],
        ["nr_keira", 1],
        ["nr_dijkstra", 1],
        ["nr_sheala", 1],
        ["nr_thaler", 1],
        ["ntr_triss", 1],
        ["nr_olgierd", 1],
        ["nr_kaedwen_siege_1", 1],
        ["nr_kaedwen_siege_2", 1],
        ["nr_siege_tower", 1],
        ["nr_ballista_1", 1],
        ["nr_ballista_2", 1],
        ["nr_zoltan", 1],
        ["nr_sheldon", 1],
        ["nr_crinfrid_1", 1],
        ["nr_crinfrid_2", 1],
        ["nr_crinfrid_3", 1],
        ["nr_villen", 1],
        ["nr_blue_stripes_1", 1],
        ["nr_blue_stripes_2", 1],
        ["nr_blue_stripes_3", 1],
        ["nr_poor_infantry_1", 1],
        ["nr_poor_infantry_2", 1],
        ["nr_poor_infantry_3", 1],
        ["nr_banner_nurse", 1]
    ]
},
{
    "title": "Northern Realms",
    "description": "",
    "leader": "nr_foltest_son_of_medell",
    "faction": "realms",
    "cards": [
        ["spe_horn", 1],
        ["spe_decoy", 2],
        ["spe_scorch", 1],
        ["spe_clear", 1],
        ["ntr_mysterious_elf", 1],
        ["spe_rain", 1],
        ["ntr_ciri", 1],
        ["ntr_geralt", 1],
        ["nr_natalis", 1],
        ["nr_vernon", 1],
        ["nr_stennis", 1],
        ["nr_keira", 1],
        ["nr_dijkstra", 1],
        ["nr_philippa", 1],
        ["nr_thaler", 1],
        ["ntr_triss", 1],
        ["nr_olgierd", 1],
        ["nr_crinfrid_1", 1],
        ["nr_crinfrid_2", 1],
        ["nr_crinfrid_3", 1],
        ["nr_villen", 1],
        ["nr_blue_stripes_1", 1],
        ["nr_blue_stripes_2", 1],
        ["nr_blue_stripes_3", 1],
        ["nr_kaedwen_siege_1", 1],
        ["nr_kaedwen_siege_2", 1],
        ["nr_ballista_1", 1],
        ["nr_ballista_2", 1],
        ["nr_zoltan", 1],
        ["nr_siege_tower", 1],
        ["nr_poor_infantry_1", 1],
        ["nr_poor_infantry_2", 1],
        ["nr_poor_infantry_3", 1],
        ["nr_banner_nurse", 1]
    ]
},
{
    "title": "Nilfgaard",
    "description": "Deck relying mostly on Spies, Emissaries, some Tight Bond and strong ranged units",
    "leader": "ne_emhyr_invader_of_the_north",
    "faction": "nilfgaard",
    "cards": [
        ["spe_horn", 1],
        ["spe_decoy", 2],
        ["spe_scorch", 1],
        ["spe_clear", 1],
        ["ntr_ciri", 1],
        ["ntr_geralt", 1],
        ["ntr_yennefer", 1],
        ["ne_black_archer", 1],
        ["ne_black_archer_1", 1],
        ["ne_letho", 1],
        ["ne_moorvran", 1],
        ["ne_stefan", 1],
        ["ne_shilard", 1],
        ["ne_young_emissary_1", 1],
        ["ne_young_emissary_2", 1],
        ["ne_vattier", 1],
        ["ne_impera_brigade_1", 1],
        ["ne_impera_brigade_2", 1],
        ["ne_impera_brigade_3", 1],
        ["ne_impera_brigade_4", 1],
        ["ne_archer_support", 1],
        ["ne_archer_support_1", 1],
        ["ne_cahir", 1],
        ["ne_renuald", 1],
        ["ne_vreemde", 1],
        ["ne_morteisen", 1],
        ["ne_albrich", 1],
    ]
    },
{
    "title": "Nilfgaard",
    "description": "Deck relying mostly on Spies, Emissaries, some Tight Bond and strong ranged units",
    "leader": "ne_emhyr_imperial",
    "faction": "nilfgaard",
    "cards": [
        ["spe_horn", 1],
        ["spe_decoy", 2],
        ["spe_scorch", 1],
        ["spe_clear", 1],
        ["ntr_ciri", 1],
        ["ntr_geralt", 1],
        ["ntr_yennefer", 1],
        ["ne_black_archer", 1],
        ["ne_black_archer_1", 1],
        ["ne_letho", 1],
        ["ne_moorvran", 1],
        ["ne_stefan", 1],
        ["ne_shilard", 1],
        ["ne_young_emissary_1", 1],
        ["ne_young_emissary_2", 1],
        ["ne_vattier", 1],
        ["ne_impera_brigade_1", 1],
        ["ne_impera_brigade_2", 1],
        ["ne_impera_brigade_3", 1],
        ["ne_impera_brigade_4", 1],
        ["ne_archer_support", 1],
        ["ne_archer_support_1", 1],
        ["ne_cahir", 1],
        ["ne_renuald", 1],
        ["ne_vreemde", 1],
        ["ne_morteisen", 1],
        ["ne_albrich", 1],
    ]
    },
{
    "title": "Nilfgaard",
    "description": "Deck relying mostly on Spies, Emissaries, some Tight Bond and strong ranged units",
    "leader": "ne_emhyr_emperor",
    "faction": "nilfgaard",
    "cards": [
        ["spe_horn", 1],
        ["spe_decoy", 2],
        ["spe_scorch", 1],
        ["spe_clear", 1],
        ["ntr_ciri", 1],
        ["ntr_geralt", 1],
        ["ntr_yennefer", 1],
        ["ne_black_archer", 1],
        ["ne_black_archer_1", 1],
        ["ne_letho", 1],
        ["ne_moorvran", 1],
        ["ne_stefan", 1],
        ["ne_shilard", 1],
        ["ne_young_emissary_1", 1],
        ["ne_young_emissary_2", 1],
        ["ne_vattier", 1],
        ["ne_impera_brigade_1", 1],
        ["ne_impera_brigade_2", 1],
        ["ne_impera_brigade_3", 1],
        ["ne_impera_brigade_4", 1],
        ["ne_archer_support", 1],
        ["ne_archer_support_1", 1],
        ["ne_cahir", 1],
        ["ne_renuald", 1],
        ["ne_vreemde", 1],
        ["ne_morteisen", 1],
        ["ne_albrich", 1],
    ]
    },
{
    "title": "Nilfgaard",
    "description": "",
    "leader": "ne_emhyr_whiteflame",
    "faction": "nilfgaard",
    "cards": [
        ["spe_horn", 1],
        ["spe_decoy", 2],
        ["spe_scorch", 1],
        ["spe_clear", 1],
        ["ntr_ciri", 1],
        ["ntr_geralt", 1],
        ["ntr_yennefer", 1],
        ["ne_black_archer", 1],
        ["ne_black_archer_1", 1],
        ["ne_letho", 1],
        ["ne_moorvran", 1],
        ["ne_stefan", 1],
        ["ne_shilard", 1],
        ["ne_young_emissary_1", 1],
        ["ne_young_emissary_2", 1],
        ["ne_vattier", 1],
        ["ne_impera_brigade_1", 1],
        ["ne_impera_brigade_2", 1],
        ["ne_impera_brigade_3", 1],
        ["ne_impera_brigade_4", 1],
        ["ne_archer_support", 1],
        ["ne_archer_support_1", 1],
        ["ne_cahir", 1],
        ["ne_renuald", 1],
        ["ne_vreemde", 1],
        ["ne_morteisen", 1],
        ["ne_albrich", 1],
    ]
    },
{
    "title": "Nilfgaard",
    "description": "",
    "leader": "ne_emhyr_relentless",
    "faction": "nilfgaard",
    "cards": [
        ["spe_horn", 1],
        ["spe_decoy", 2],
        ["spe_scorch", 1],
        ["spe_clear", 1],
        ["ntr_ciri", 1],
        ["ntr_geralt", 1],
        ["ntr_yennefer", 1],
        ["ne_black_archer", 1],
        ["ne_black_archer_1", 1],
        ["ne_letho", 1],
        ["ne_moorvran", 1],
        ["ne_stefan", 1],
        ["ne_shilard", 1],
        ["ne_young_emissary_1", 1],
        ["ne_young_emissary_2", 1],
        ["ne_vattier", 1],
        ["ne_impera_brigade_1", 1],
        ["ne_impera_brigade_2", 1],
        ["ne_impera_brigade_3", 1],
        ["ne_impera_brigade_4", 1],
        ["ne_archer_support", 1],
        ["ne_archer_support_1", 1],
        ["ne_cahir", 1],
        ["ne_renuald", 1],
        ["ne_vreemde", 1],
        ["ne_morteisen", 1],
        ["ne_albrich", 1],
    ]
    },
    {
        "title": "Monsters",
        "description": "Deck relying on a lot of muster units",
        "leader": "mo_eredin_commander",
        "faction": "monsters",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 1],
            ["spe_scorch", 1],
            ["spe_clear", 1],
            ["spe_fog", 1],
            ["spe_rain", 1],
            ["mo_draug", 1],
            ["mo_imlerith", 1],
            ["mo_leshen", 1],
            ["mo_gaunter_odimm", 1],
            ["mo_kayran", 1],
            ["mo_witch_velen", 1],
            ["mo_witch_velen_1", 1],
            ["mo_witch_velen_2", 1],
            ["mo_foglet", 1],
            ["mo_arachas_behemoth", 1],
            ["mo_nekker", 1],
            ["mo_nekker_1", 1],
            ["mo_nekker_2", 1],
            ["mo_toad", 1],
            ["mo_katakan", 1],
            ["mo_arachas", 1],
            ["mo_arachas_1", 1],
            ["mo_arachas_2", 1],
            ["mo_plague_maiden", 1],
            ["mo_bruxa", 1],
            ["mo_ekkima", 1],
            ["mo_fleder", 1],
            ["mo_garkain", 1],
            ["mo_gaunter_odimm_darkness", 1]
        ]
    },
 {
        "title": "Monsters",
        "description": "Deck relying on a lot of muster units",
        "leader": "mo_eredin_bringer_of_death",
        "faction": "monsters",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 1],
            ["spe_scorch", 1],
            ["spe_clear", 1],
            ["spe_fog", 1],
            ["spe_rain", 1],
            ["mo_draug", 1],
            ["mo_imlerith", 1],
            ["mo_leshen", 1],
            ["mo_gaunter_odimm", 1],
            ["mo_kayran", 1],
            ["mo_witch_velen", 1],
            ["mo_witch_velen_1", 1],
            ["mo_witch_velen_2", 1],
            ["mo_foglet", 1],
            ["mo_arachas_behemoth", 1],
            ["mo_nekker", 1],
            ["mo_nekker_1", 1],
            ["mo_nekker_2", 1],
            ["mo_toad", 1],
            ["mo_katakan", 1],
            ["mo_arachas", 1],
            ["mo_arachas_1", 1],
            ["mo_arachas_2", 1],
            ["mo_plague_maiden", 1],
            ["mo_bruxa", 1],
            ["mo_ekkima", 1],
            ["mo_fleder", 1],
            ["mo_garkain", 1],
            ["mo_gaunter_odimm_darkness", 1]
        ]
    },
 {
        "title": "Monsters",
        "description": "Deck relying on a lot of muster units",
        "leader": "mo_eredin_destroyer",
        "faction": "monsters",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 1],
            ["spe_scorch", 1],
            ["spe_clear", 1],
            ["spe_fog", 1],
            ["spe_rain", 1],
            ["mo_draug", 1],
            ["mo_imlerith", 1],
            ["mo_leshen", 1],
            ["mo_gaunter_odimm", 1],
            ["mo_kayran", 1],
            ["mo_witch_velen", 1],
            ["mo_witch_velen_1", 1],
            ["mo_witch_velen_2", 1],
            ["mo_foglet", 1],
            ["mo_arachas_behemoth", 1],
            ["mo_nekker", 1],
            ["mo_nekker_1", 1],
            ["mo_nekker_2", 1],
            ["mo_toad", 1],
            ["mo_katakan", 1],
            ["mo_arachas", 1],
            ["mo_arachas_1", 1],
            ["mo_arachas_2", 1],
            ["mo_plague_maiden", 1],
            ["mo_bruxa", 1],
            ["mo_ekkima", 1],
            ["mo_fleder", 1],
            ["mo_garkain", 1],
            ["mo_gaunter_odimm_darkness", 1]
        ]
    },
 {
        "title": "Monsters",
        "description": "Deck relying on a lot of muster units",
        "leader": "mo_eredin_king",
        "faction": "monsters",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 1],
            ["spe_scorch", 1],
            ["spe_clear", 1],
            ["spe_fog", 1],
            ["spe_rain", 1],
            ["mo_draug", 1],
            ["mo_imlerith", 1],
            ["mo_leshen", 1],
            ["mo_gaunter_odimm", 1],
            ["mo_kayran", 1],
            ["mo_witch_velen", 1],
            ["mo_witch_velen_1", 1],
            ["mo_witch_velen_2", 1],
            ["mo_foglet", 1],
            ["mo_arachas_behemoth", 1],
            ["mo_nekker", 1],
            ["mo_nekker_1", 1],
            ["mo_nekker_2", 1],
            ["mo_toad", 1],
            ["mo_katakan", 1],
            ["mo_arachas", 1],
            ["mo_arachas_1", 1],
            ["mo_arachas_2", 1],
            ["mo_plague_maiden", 1],
            ["mo_bruxa", 1],
            ["mo_ekkima", 1],
            ["mo_fleder", 1],
            ["mo_garkain", 1],
            ["mo_gaunter_odimm_darkness", 1]
        ]
    },
 {
        "title": "Monsters",
        "description": "Deck relying on a lot of muster units",
        "leader": "mo_eredin_the_treacherous",
        "faction": "monsters",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 1],
            ["spe_scorch", 1],
            ["spe_clear", 1],
            ["spe_fog", 1],
            ["spe_rain", 1],
            ["mo_draug", 1],
            ["mo_imlerith", 1],
            ["mo_leshen", 1],
            ["mo_gaunter_odimm", 1],
            ["mo_kayran", 1],
            ["mo_witch_velen", 1],
            ["mo_witch_velen_1", 1],
            ["mo_witch_velen_2", 1],
            ["mo_foglet", 1],
            ["mo_arachas_behemoth", 1],
            ["mo_nekker", 1],
            ["mo_nekker_1", 1],
            ["mo_nekker_2", 1],
            ["mo_toad", 1],
            ["mo_katakan", 1],
            ["mo_arachas", 1],
            ["mo_arachas_1", 1],
            ["mo_arachas_2", 1],
            ["mo_plague_maiden", 1],
            ["mo_bruxa", 1],
            ["mo_ekkima", 1],
            ["mo_fleder", 1],
            ["mo_garkain", 1],
            ["mo_gaunter_odimm_darkness", 1]
        ]
    },
    {
        "title": "Scoia'Tael",
        "description": "Deck relying on agile units and muster",
        "leader": "sc_francesca_pureblood",
        "faction": "scoiatael",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 1],
            ["spe_scorch", 1],
            ["spe_clear", 1],
            ["spe_frost", 1],
            ["spe_rain", 1],
            ["sc_iorveth", 1],
            ["sc_isengrim", 1],
            ["sc_schirru", 1],
            ["sc_mahakam", 1],
            ["sc_mahakam_1", 1],
            ["sc_saskia", 1],
            ["sc_vrihedd_brigade_1", 1],
            ["sc_vrihedd_brigade", 1],
            ["ntr_mysterious_elf", 1],
            ["sc_filavandrel", 1],
            ["sc_toruviel", 1],
            ["sc_yaevinn", 1],
            ["sc_dol_infantry_1", 1],
            ["sc_dol_infantry_2", 1],
            ["sc_havekar_support", 1],
            ["sc_havekar_support_1", 1],
            ["sc_havekar_support_2", 1],
            ["sc_elf_skirmisher", 1],
            ["sc_elf_skirmisher_1", 1],
            ["sc_elf_skirmisher_2", 1],
            ["sc_vrihedd_cadet", 1],
            ["sc_havekar_nurse", 1],
            ["sc_havekar_nurse_2", 1],
            ["sc_temptress", 1]
        ]
    },
 {
        "title": "Scoia'Tael",
        "description": "Deck relying on agile units and muster",
        "leader": "sc_francesca_hope_of_the_aen_seidhe",
        "faction": "scoiatael",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 1],
            ["spe_scorch", 1],
            ["spe_clear", 1],
            ["spe_frost", 1],
            ["spe_rain", 1],
            ["sc_iorveth", 1],
            ["sc_isengrim", 1],
            ["sc_schirru", 1],
            ["sc_mahakam", 1],
            ["sc_mahakam_1", 1],
            ["sc_saskia", 1],
            ["sc_vrihedd_brigade_1", 1],
            ["sc_vrihedd_brigade", 1],
            ["ntr_mysterious_elf", 1],
            ["sc_filavandrel", 1],
            ["sc_toruviel", 1],
            ["sc_yaevinn", 1],
            ["sc_dol_infantry_1", 1],
            ["sc_dol_infantry_2", 1],
            ["sc_havekar_support", 1],
            ["sc_havekar_support_1", 1],
            ["sc_havekar_support_2", 1],
            ["sc_elf_skirmisher", 1],
            ["sc_elf_skirmisher_1", 1],
            ["sc_elf_skirmisher_2", 1],
            ["sc_vrihedd_cadet", 1],
            ["sc_havekar_nurse", 1],
            ["sc_havekar_nurse_2", 1],
            ["sc_temptress", 1]
        ]
    },
 {
        "title": "Scoia'Tael",
        "description": "Deck relying on agile units and muster",
        "leader": "sc_francesca_daisy",
        "faction": "scoiatael",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 1],
            ["spe_scorch", 1],
            ["spe_clear", 1],
            ["spe_frost", 1],
            ["spe_rain", 1],
            ["sc_iorveth", 1],
            ["sc_isengrim", 1],
            ["sc_schirru", 1],
            ["sc_mahakam", 1],
            ["sc_mahakam_1", 1],
            ["sc_saskia", 1],
            ["sc_vrihedd_brigade_1", 1],
            ["sc_vrihedd_brigade", 1],
            ["ntr_mysterious_elf", 1],
            ["sc_filavandrel", 1],
            ["sc_toruviel", 1],
            ["sc_yaevinn", 1],
            ["sc_dol_infantry_1", 1],
            ["sc_dol_infantry_2", 1],
            ["sc_havekar_support", 1],
            ["sc_havekar_support_1", 1],
            ["sc_havekar_support_2", 1],
            ["sc_elf_skirmisher", 1],
            ["sc_elf_skirmisher_1", 1],
            ["sc_elf_skirmisher_2", 1],
            ["sc_vrihedd_cadet", 1],
            ["sc_havekar_nurse", 1],
            ["sc_havekar_nurse_2", 1],
            ["sc_temptress", 1]
        ]
    },
 {
        "title": "Scoia'Tael",
        "description": "Deck relying on agile units and muster",
        "leader": "sc_francesca_beautiful",
        "faction": "scoiatael",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 1],
            ["spe_scorch", 1],
            ["spe_clear", 1],
            ["spe_frost", 1],
            ["spe_rain", 1],
            ["sc_iorveth", 1],
            ["sc_isengrim", 1],
            ["sc_schirru", 1],
            ["sc_mahakam", 1],
            ["sc_mahakam_1", 1],
            ["sc_saskia", 1],
            ["sc_vrihedd_brigade_1", 1],
            ["sc_vrihedd_brigade", 1],
            ["ntr_mysterious_elf", 1],
            ["sc_filavandrel", 1],
            ["sc_toruviel", 1],
            ["sc_yaevinn", 1],
            ["sc_dol_infantry_1", 1],
            ["sc_dol_infantry_2", 1],
            ["sc_havekar_support", 1],
            ["sc_havekar_support_1", 1],
            ["sc_havekar_support_2", 1],
            ["sc_elf_skirmisher", 1],
            ["sc_elf_skirmisher_1", 1],
            ["sc_elf_skirmisher_2", 1],
            ["sc_vrihedd_cadet", 1],
            ["sc_havekar_nurse", 1],
            ["sc_havekar_nurse_2", 1],
            ["sc_temptress", 1]
        ]
    },
 {
        "title": "Scoia'Tael",
        "description": "Deck relying on agile units and muster",
        "leader": "sc_francesca_queen",
        "faction": "scoiatael",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 1],
            ["spe_scorch", 1],
            ["spe_clear", 1],
            ["spe_frost", 1],
            ["spe_rain", 1],
            ["sc_iorveth", 1],
            ["sc_isengrim", 1],
            ["sc_schirru", 1],
            ["sc_mahakam", 1],
            ["sc_mahakam_1", 1],
            ["sc_saskia", 1],
            ["sc_vrihedd_brigade_1", 1],
            ["sc_vrihedd_brigade", 1],
            ["ntr_mysterious_elf", 1],
            ["sc_filavandrel", 1],
            ["sc_toruviel", 1],
            ["sc_yaevinn", 1],
            ["sc_dol_infantry_1", 1],
            ["sc_dol_infantry_2", 1],
            ["sc_havekar_support", 1],
            ["sc_havekar_support_1", 1],
            ["sc_havekar_support_2", 1],
            ["sc_elf_skirmisher", 1],
            ["sc_elf_skirmisher_1", 1],
            ["sc_elf_skirmisher_2", 1],
            ["sc_vrihedd_cadet", 1],
            ["sc_havekar_nurse", 1],
            ["sc_havekar_nurse_2", 1],
            ["sc_temptress", 1]
        ]
    },
    {
        "title": "Skellige",
        "description": "Deck relying mostly on berserker units",
        "leader": "sk_holger",
        "faction": "skellige",
        "cards": [
            ["spe_mardroeme", 2],
            ["spe_skellige_fleet", 2],
            ["spe_horn", 1],
            ["spe_decoy", 1],
            ["spe_scorch", 1],
            ["spe_clear", 1],
            ["spe_frost", 1],
            ["spe_rain", 1],
            ["sk_hjalmar", 1],
            ["sk_brokva_archer", 1],
            ["sk_cerys", 1],
            ["sk_ermion", 1],
            ["ntr_yennefer", 1],
            ["sk_longship_1", 1],
            ["sk_longship_3", 1],
            ["sk_longship_2", 1],
            ["sk_berserker", 1],
            ["sk_shield_maiden_1", 1],
            ["sk_shield_maiden_2", 1],
            ["sk_shield_maiden_3", 1],
            ["sk_light_longship_1", 1],
            ["sk_light_longship_2", 1],
            ["sk_light_longship_3", 1],
            ["sk_vildkaarl", 1],
            ["sk_gremist", 1],
            ["sk_young_berserker_1", 1],
            ["sk_young_berserker_2", 1],
            ["sk_young_berserker_3", 1],
            ["sk_arnvald", 1],
            ["sk_kambi", 1]
        ]
    },
   {
        "title": "Skellige",
        "description": "Deck relying mostly on berserker units",
        "leader": "sk_king_bran",
        "faction": "skellige",
        "cards": [
            ["spe_mardroeme", 2],
            ["spe_skellige_fleet", 2],
            ["spe_horn", 1],
            ["spe_decoy", 1],
            ["spe_scorch", 1],
            ["spe_clear", 1],
            ["spe_frost", 1],
            ["spe_rain", 1],
            ["sk_hjalmar", 1],
            ["sk_brokva_archer", 1],
            ["sk_cerys", 1],
            ["sk_ermion", 1],
            ["ntr_yennefer", 1],
            ["sk_longship_1", 1],
            ["sk_longship_3", 1],
            ["sk_longship_2", 1],
            ["sk_berserker", 1],
            ["sk_shield_maiden_1", 1],
            ["sk_shield_maiden_2", 1],
            ["sk_shield_maiden_3", 1],
            ["sk_light_longship_1", 1],
            ["sk_light_longship_2", 1],
            ["sk_light_longship_3", 1],
            ["sk_vildkaarl", 1],
            ["sk_gremist", 1],
            ["sk_young_berserker_1", 1],
            ["sk_young_berserker_2", 1],
            ["sk_young_berserker_3", 1],
            ["sk_arnvald", 1],
            ["sk_kambi", 1]
        ]
    },
   {
        "title": "Skellige",
        "description": "Deck relying mostly on berserker units",
        "leader": "sk_birna",
        "faction": "skellige",
        "cards": [
            ["spe_mardroeme", 2],
            ["spe_skellige_fleet", 2],
            ["spe_horn", 1],
            ["spe_decoy", 1],
            ["spe_scorch", 1],
            ["spe_clear", 1],
            ["spe_frost", 1],
            ["spe_rain", 1],
            ["sk_hjalmar", 1],
            ["sk_brokva_archer", 1],
            ["sk_cerys", 1],
            ["sk_ermion", 1],
            ["ntr_yennefer", 1],
            ["sk_longship_1", 1],
            ["sk_longship_3", 1],
            ["sk_longship_2", 1],
            ["sk_berserker", 1],
            ["sk_shield_maiden_1", 1],
            ["sk_shield_maiden_2", 1],
            ["sk_shield_maiden_3", 1],
            ["sk_light_longship_1", 1],
            ["sk_light_longship_2", 1],
            ["sk_light_longship_3", 1],
            ["sk_vildkaarl", 1],
            ["sk_gremist", 1],
            ["sk_young_berserker_1", 1],
            ["sk_young_berserker_2", 1],
            ["sk_young_berserker_3", 1],
            ["sk_arnvald", 1],
            ["sk_kambi", 1]
        ]
    },
   {
        "title": "Skellige",
        "description": "Deck relying mostly on berserker units",
        "leader": "sk_madman_lugos",
        "faction": "skellige",
        "cards": [
            ["spe_mardroeme", 2],
            ["spe_skellige_fleet", 2],
            ["spe_horn", 1],
            ["spe_decoy", 1],
            ["spe_scorch", 1],
            ["spe_clear", 1],
            ["spe_frost", 1],
            ["spe_rain", 1],
            ["sk_hjalmar", 1],
            ["sk_brokva_archer", 1],
            ["sk_cerys", 1],
            ["sk_ermion", 1],
            ["ntr_yennefer", 1],
            ["sk_longship_1", 1],
            ["sk_longship_3", 1],
            ["sk_longship_2", 1],
            ["sk_berserker", 1],
            ["sk_shield_maiden_1", 1],
            ["sk_shield_maiden_2", 1],
            ["sk_shield_maiden_3", 1],
            ["sk_light_longship_1", 1],
            ["sk_light_longship_2", 1],
            ["sk_light_longship_3", 1],
            ["sk_vildkaarl", 1],
            ["sk_gremist", 1],
            ["sk_young_berserker_1", 1],
            ["sk_young_berserker_2", 1],
            ["sk_young_berserker_3", 1],
            ["sk_arnvald", 1],
            ["sk_kambi", 1]
        ]
    },
   {
        "title": "Witcher Universe",
        "description": "Witcher Universe deck focusing on witcher schools - Playstyle: Witcher Schools, Resilience, Scorch",
        "leader": "wu_cosimo_malaspina",
        "faction": "witcher_universe",
        "cards": [
            ["wu_coen", 1],
            ["wu_stygga_castle", 1],
            ["ntr_vesemir", 1],
            ["wu_haern_caduch", 1],
            ["wu_ivo_belhaven", 1],
            ["wu_lambert", 1],
            ["wu_keldar", 1],
            ["wu_ivar", 1],
            ["wu_gorthur_gvaed", 1],
            ["wu_kaer_morhen", 1],
            ["wu_kaer_seren", 1],
            ["wu_gezras", 1],
            ["ntr_geralt", 1],
            ["wu_gaetan", 1],
            ["wu_brehen", 1],
            ["wu_gerd", 1],
            ["wu_warrit", 1],
            ["wu_erland", 1],
            ["wu_arnaghad", 1],
            ["wu_letho", 1],
            ["wu_eskel", 1],
            ["wu_kolgrim", 1],
            ["spe_sign_igni", 2],
            ["spe_sign_quen", 2],
            ["spe_sign_axii", 2],
            ["spe_sign_aard", 2],
            ["spe_sign_yrden", 2],
            ["wu_swallow_potion", 1],
        ]
    },
 {
        "title": "Witcher Universe",
        "description": "Witcher Universe deck focusing on witcher schools - Playstyle: Witcher Schools, Resilience, Scorch",
        "leader": "wu_vilgefortz_magician_kovir",
        "faction": "witcher_universe",
        "cards": [
            ["wu_coen", 1],
            ["wu_stygga_castle", 1],
            ["ntr_vesemir", 1],
            ["wu_haern_caduch", 1],
            ["wu_ivo_belhaven", 1],
            ["wu_lambert", 1],
            ["wu_keldar", 1],
            ["wu_ivar", 1],
            ["wu_gorthur_gvaed", 1],
            ["wu_kaer_morhen", 1],
            ["wu_kaer_seren", 1],
            ["wu_gezras", 1],
            ["ntr_geralt", 1],
            ["wu_gaetan", 1],
            ["wu_brehen", 1],
            ["wu_gerd", 1],
            ["wu_warrit", 1],
            ["wu_erland", 1],
            ["wu_arnaghad", 1],
            ["wu_letho", 1],
            ["wu_eskel", 1],
            ["wu_kolgrim", 1],
            ["spe_sign_igni", 2],
            ["spe_sign_quen", 2],
            ["spe_sign_axii", 2],
            ["spe_sign_aard", 2],
            ["spe_sign_yrden", 2],
            ["wu_swallow_potion", 1],
        ]
    },
 {
        "title": "Witcher Universe",
        "description": "Witcher Universe deck focusing on witcher schools - Playstyle: Witcher Schools, Resilience, Scorch",
        "leader": "wu_alzur_maker",
        "faction": "witcher_universe",
        "cards": [
            ["wu_coen", 1],
            ["wu_stygga_castle", 1],
            ["ntr_vesemir", 1],
            ["wu_haern_caduch", 1],
            ["wu_ivo_belhaven", 1],
            ["wu_lambert", 1],
            ["wu_keldar", 1],
            ["wu_ivar", 1],
            ["wu_gorthur_gvaed", 1],
            ["wu_kaer_morhen", 1],
            ["wu_kaer_seren", 1],
            ["wu_gezras", 1],
            ["ntr_geralt", 1],
            ["wu_gaetan", 1],
            ["wu_brehen", 1],
            ["wu_gerd", 1],
            ["wu_warrit", 1],
            ["wu_erland", 1],
            ["wu_arnaghad", 1],
            ["wu_letho", 1],
            ["wu_eskel", 1],
            ["wu_kolgrim", 1],
            ["spe_sign_igni", 2],
            ["spe_sign_quen", 2],
            ["spe_sign_axii", 2],
            ["spe_sign_aard", 2],
            ["spe_sign_yrden", 2],
            ["wu_swallow_potion", 1],
        ]
    },
 {
        "title": "Witcher Universe",
        "description": "Witcher Universe deck focusing on witcher schools - Playstyle: Witcher Schools, Resilience, Scorch",
        "leader": "wu_vilgefortz_sorcerer",
        "faction": "witcher_universe",
        "cards": [
            ["wu_coen", 1],
            ["wu_stygga_castle", 1],
            ["ntr_vesemir", 1],
            ["wu_haern_caduch", 1],
            ["wu_ivo_belhaven", 1],
            ["wu_lambert", 1],
            ["wu_keldar", 1],
            ["wu_ivar", 1],
            ["wu_gorthur_gvaed", 1],
            ["wu_kaer_morhen", 1],
            ["wu_kaer_seren", 1],
            ["wu_gezras", 1],
            ["ntr_geralt", 1],
            ["wu_gaetan", 1],
            ["wu_brehen", 1],
            ["wu_gerd", 1],
            ["wu_warrit", 1],
            ["wu_erland", 1],
            ["wu_arnaghad", 1],
            ["wu_letho", 1],
            ["wu_eskel", 1],
            ["wu_kolgrim", 1],
            ["spe_sign_igni", 2],
            ["spe_sign_quen", 2],
            ["spe_sign_axii", 2],
            ["spe_sign_aard", 2],
            ["spe_sign_yrden", 2],
            ["wu_swallow_potion", 1],
        ]
    },
     {
        "title": "Redania",
        "description": "Deck relying mostly on witch hunters",
        "leader": "re_radovid_mad_king",
        "faction": "redania",
        "cards": [
            ["spe_horn", 2],
            ["spe_decoy", 2],
            ["spe_execution", 1],
            ["spe_royal_decree", 2],
            ["spe_clear", 1],
            ["spe_rain", 1],
            ["re_black_cat_dog", 1],
            ["re_redanian_elite", 1],
            ["re_ewald_borsodi", 1],
            ["re_caretaker", 1],
            ["re_horst_borsodi", 1],
            ["re_redanian_knight_1", 1],
            ["re_redanian_knight_2", 1],
            ["re_graden", 1],
            ["re_shani", 1],
            ["re_olgierd", 1],
            ["re_vlodimir_von_everec", 1],
            ["re_sigi_reuven", 1],
            ["re_foot_soldier_1", 1],
            ["re_foot_soldier_2", 1],
            ["re_agent", 1],
            ["re_archer", 1],
            ["re_priscilla", 1],
            ["re_phillippa", 1],
            ["re_iris_von_everec", 1],
            ["re_trollololo", 1],
            ["ntr_geralt", 1],
            ["ntr_yennefer", 1],
            ["re_gaunter_odimm", 1],
            ["re_gaunter_odimm_darkness", 3],
        ]
    },
{
        "title": "Redania",
        "description": "Deck relying mostly on witch hunters",
        "leader": "re_radovid_king_redania",
        "faction": "redania",
        "cards": [
            ["spe_horn", 2],
            ["spe_decoy", 2],
            ["spe_execution", 1],
            ["spe_royal_decree", 2],
            ["spe_clear", 1],
            ["spe_rain", 1],
            ["ntr_triss", 1],
            ["ntr_ciri", 1],
            ["re_black_cat_dog", 1],
            ["re_redanian_elite", 1],
            ["re_caretaker", 1],
            ["re_redanian_knight_1", 1],
            ["re_redanian_knight_2", 1],
            ["re_graden", 1],
            ["re_shani", 1],
            ["re_olgierd", 1],
            ["re_vlodimir_von_everec", 1],
            ["re_sigi_reuven", 1],
            ["re_iris_von_everec", 1],
            ["re_phillippa", 1],
            ["re_iris_von_everec", 1],
            ["re_trollololo", 1],
            ["ntr_geralt", 1],
            ["re_foot_soldier_1", 1],
            ["re_foot_soldier_2", 1],
            ["ntr_mysterious_elf", 1],
            ["ntr_dandelion", 1],
            ["re_ewald_borsodi", 1],
            ["re_gaunter_odimm_darkness", 3],
            ["re_archer", 1],
        ]
    },
{
        "title": "Redania",
        "description": "Deck relying mostly on witch hunters",
        "leader": "re_radovid_strategist",
        "faction": "redania",
        "cards": [
            ["spe_horn", 2],
            ["spe_decoy", 2],
            ["spe_execution", 2],
            ["spe_royal_decree", 2],
            ["spe_clear", 1],
            ["spe_rain", 1],
            ["re_black_cat_dog", 1],
            ["re_redanian_elite", 1],
            ["re_caretaker", 1],
            ["re_redanian_knight_1", 1],
            ["re_redanian_knight_2", 1],
            ["re_graden", 1],
            ["re_shani", 1],
            ["re_olgierd", 1],
            ["re_vlodimir_von_everec", 1],
            ["re_sigi_reuven", 1],
            ["re_iris_von_everec", 1],
            ["re_gaunter_odimm_darkness", 3],
            ["re_foot_soldier_1", 1],
            ["re_foot_soldier_2", 1],
            ["re_phillippa", 1],
            ["re_agent", 1],
            ["re_archer", 1],
            ["re_trollololo", 1],
            ["ntr_geralt", 1],
            ["re_priscilla", 1],
            ["ntr_triss", 1],
            ["ntr_ciri", 1],
            ["ntr_mysterious_elf", 1],
            ["ntr_dandelion", 1],
        ]
    },

    {
        "title": "Toussaint",
        "description": "Deck relying mostly Toussaint monsters, spies and muster",
        "leader": "to_anna_henrietta_little_weasel",
        "faction": "toussaint",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 2],
            ["spe_scorch", 1],
            ["spe_toussaint_wine", 2],
            ["spe_clear", 1],
            ["to_unseen_elder", 1],
            ["to_damien_tour", 1],
            ["to_roderick", 1],
            ["to_gregoire_gorgon", 1],
            ["to_witch_lynx_crag", 1],
            ["to_milton", 1],
            ["to_champion", 1],
            ["to_duchess_informant", 1],
            ["to_syanna", 1],
            ["to_bootblack", 1],
            ["ntr_geralt", 1],
            ["to_dettlaff", 1],
            ["to_knight_errant_1", 1],
            ["to_knight_errant_2", 1],
            ["to_lui_alberni", 1],
            ["to_orianna", 1],
            ["to_regis", 1],
            ["to_prophet_lebioda", 1],
            ["to_toussaint_knight_1", 1],
            ["to_toussaint_knight_2", 1],
            ["to_toussaint_knight_3", 1],
            ["to_artorius_vigo", 1],
            ["to_lady_lake", 1],
            ["to_vivienne", 1]
        ]
    },
{
        "title": "Toussaint",
        "description": "Deck relying mostly Toussaint monsters, spies and muster",
        "leader": "to_anna_henrietta_duchess",
        "faction": "toussaint",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 2],
            ["spe_scorch", 1],
            ["ntr_geralt", 1],
            ["spe_toussaint_wine", 2],
            ["spe_clear", 1],
            ["to_unseen_elder", 1],
            ["to_damien_tour", 1],
            ["to_roderick", 1],
            ["to_gregoire_gorgon", 1],
            ["to_witch_lynx_crag", 1],
            ["to_milton", 1],
            ["to_champion", 1],
            ["to_duchess_informant", 1],
            ["to_syanna", 1],
            ["to_bootblack", 1],
            ["to_dettlaff", 1],
            ["to_knight_errant_1", 1],
            ["to_knight_errant_2", 1],
            ["to_lui_alberni", 1],
            ["to_orianna", 1],
            ["to_regis", 1],
            ["to_prophet_lebioda", 1],
            ["to_toussaint_knight_1", 1],
            ["to_toussaint_knight_2", 1],
            ["to_toussaint_knight_3", 1],
            ["to_artorius_vigo", 1],
            ["to_lady_lake", 1],
            ["to_vivienne", 1]
        ]
    },
{
        "title": "Toussaint",
        "description": "Deck relying mostly Toussaint monsters, spies and muster",
        "leader": "to_anna_henrietta_ladyship",
        "faction": "toussaint",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 2],
            ["ntr_geralt", 1],
            ["spe_scorch", 1],
            ["spe_toussaint_wine", 2],
            ["spe_clear", 1],
            ["to_unseen_elder", 1],
            ["to_damien_tour", 1],
            ["to_roderick", 1],
            ["to_gregoire_gorgon", 1],
            ["to_witch_lynx_crag", 1],
            ["to_milton", 1],
            ["to_champion", 1],
            ["to_duchess_informant", 1],
            ["to_syanna", 1],
            ["to_bootblack", 1],
            ["to_dettlaff", 1],
            ["to_knight_errant_1", 1],
            ["to_knight_errant_2", 1],
            ["to_lui_alberni", 1],
            ["to_orianna", 1],
            ["to_regis", 1],
            ["to_prophet_lebioda", 1],
            ["to_toussaint_knight_1", 1],
            ["to_toussaint_knight_2", 1],
            ["to_toussaint_knight_3", 1],
            ["to_artorius_vigo", 1],
            ["to_lady_lake", 1],
            ["to_vivienne", 1]
        ]
    },
  {
        "title": "Lyria & Rivia",
        "description": "Lyria & Rivia deck focusing on cards of the first line (Melee/Ranged) - Playstyle: Muster, Medic",
        "leader": "lr_meve_princess",
        "faction": "lyria_rivia",
        "cards": [
            ["spe_horn", 2],
            ["spe_watchman", 1],
            ["spe_rain", 1],
            ["spe_clear", 2],
            ["spe_scorch", 1],
            ["lr_rivian_mauler", 1],
            ["lr_grey_rider", 2],
            ["lr_prince_anseis", 1],
            ["lr_royal_guard", 1],
            ["lr_landsknecht", 3],
            ["lr_knighthood", 1],
            ["lr_reynard_odo", 1],
            ["lr_war_wagon", 1],
            ["lr_wagenburg", 3],
            ["lr_gascon", 1],
            ["lr_pikeman", 1],
            ["lr_light_cavalry", 2],
            ["lr_rayla", 1],
            ["ntr_triss", 1],
            ["lr_wagon", 1],
            ["lr_winch", 1],
            ["lr_lyrian_cavalry", 1],
            ["lr_scytheman_1", 1],
            ["lr_caldwell", 1],
            ["lr_carroballista", 1],
            ["lr_arbalest", 1],
            ["lr_hajduk", 1],
            ["ntr_geralt", 1],
            ["spe_wyvern_shield", 1],
            ["spe_mantlet", 1]
        ]
    },
  {
        "title": "Lyria & Rivia",
        "description": "Lyria & Rivia deck focusing on cards of the first line (Melee/Ranged) - Playstyle: Muster, Medic",
        "leader": "lr_meve_white_queen",
        "faction": "lyria_rivia",
        "cards": [
            ["spe_horn", 1],
            ["lr_scytheman_3", 1],
            ["lr_caldwell", 1],
            ["lr_carroballista", 1],
            ["lr_banner", 1],
            ["lr_arbalest", 1],
            ["spe_decoy", 2],
            ["spe_rain", 1],
            ["spe_clear", 1],
            ["spe_scorch", 1],
            ["lr_rivian_mauler", 1],
            ["lr_grey_rider", 2],
            ["lr_prince_anseis", 1],
            ["lr_royal_guard", 1],
            ["lr_landsknecht", 3],
            ["lr_knighthood", 1],
            ["lr_reynard_odo", 1],
            ["lr_war_wagon", 1],
            ["lr_wagenburg", 3],
            ["lr_gascon", 1],
            ["lr_pikeman", 1],
            ["lr_light_cavalry", 2],
            ["lr_rayla", 1],
            ["lr_wagon", 1],
            ["lr_lyrian_cavalry", 1],
            ["lr_hajduk", 1],
            ["ntr_geralt", 1],
            ["spe_wyvern_shield", 1],
            ["spe_mantlet", 1],
            ["ntr_ciri", 1],
            ["spe_garrison", 1]
        ]
    },
  {
        "title": "Syndicate",
        "description": "Syndicate deck focusing on cards of the Eternal Fire - Playstyle: Witch Hunt, Muster, Dimeritium",
        "leader": "sy_cyrus_hemmelfart",
        "faction": "syndicate",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 2],
            ["spe_rain", 1],
            ["spe_clear", 1],
            ["spe_dimeritium_shackles", 2],
            ["ntr_geralt", 1],
            ["sy_flaming_rose_footman", 1],
            ["sy_witch_hunter", 1],
            ["sy_witch_hunter_executioner", 1],
            ["sy_eternal_fire_inquisitor", 1],
            ["sy_caleb_menge", 1],
            ["sy_moreelse", 1],
            ["sy_jacques_aldersberg", 1],
            ["sy_temple_guard", 1],
            ["sy_roderick_wett", 1],
            ["sy_ulrich", 1],
            ["sy_walter_veritas", 1],
            ["sy_eternal_fire_priest_1", 1],
            ["sy_eternal_fire_priest_2", 1],
            ["sy_eternal_fire_priest_3", 1],
            ["sy_octavia_hale", 1],
            ["sy_fabian_hale", 1],
            ["sy_ignatius_hale", 1],
            ["sy_cleric_flaming_rose", 1],
            ["sy_eternal_fire_disciple", 2],
            ["sy_lonely_champion", 1],
            ["sy_inquisitor_helveed", 1]
        ]
    },
{
        "title": "Syndicate",
        "description": "Syndicate deck focusing on cards of the Eternal Fire - Playstyle: Witch Hunt, Muster, Dimeritium",
        "leader": "sy_carlo_varese",
        "faction": "syndicate",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 2],
            ["spe_rain", 1],
            ["spe_clear", 1],
            ["spe_dimeritium_shackles", 2],
            ["sy_flaming_rose_footman", 1],
            ["sy_witch_hunter", 1],
            ["ntr_geralt", 1],
            ["ntr_triss", 1],
            ["sy_witch_hunter_executioner", 1],
            ["sy_eternal_fire_inquisitor", 1],
            ["sy_caleb_menge", 1],
            ["sy_moreelse", 1],
            ["sy_jacques_aldersberg", 1],
            ["sy_temple_guard", 1],
            ["sy_roderick_wett", 1],
            ["sy_ulrich", 1],
            ["sy_walter_veritas", 1],
            ["sy_eternal_fire_priest_1", 1],
            ["sy_eternal_fire_priest_2", 1],
            ["sy_eternal_fire_priest_3", 1],
            ["sy_octavia_hale", 1],
            ["sy_fabian_hale", 1],
            ["sy_ignatius_hale", 1],
            ["sy_cleric_flaming_rose", 1],
            ["sy_eternal_fire_disciple", 2],
            ["sy_lonely_champion", 1],
            ["sy_inquisitor_helveed", 1]
        ]
    },
{
        "title": "Syndicate",
        "description": "Syndicate deck focusing on cards of the Eternal Fire - Playstyle: Witch Hunt, Muster, Dimeritium",
        "leader": "sy_francis_bedlam",
        "faction": "syndicate",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 2],
            ["spe_rain", 1],
            ["spe_clear", 1],
            ["spe_dimeritium_shackles", 2],
            ["sy_flaming_rose_footman", 1],
            ["sy_witch_hunter", 1],
            ["sy_witch_hunter_executioner", 1],
            ["sy_eternal_fire_inquisitor", 1],
            ["sy_caleb_menge", 1],
            ["sy_moreelse", 1],
            ["ntr_geralt", 1],
            ["sy_jacques_aldersberg", 1],
            ["sy_temple_guard", 1],
            ["sy_roderick_wett", 1],
            ["sy_ulrich", 1],
            ["sy_walter_veritas", 1],
            ["sy_eternal_fire_priest_1", 1],
            ["sy_eternal_fire_priest_2", 1],
            ["sy_eternal_fire_priest_3", 1],
            ["sy_octavia_hale", 1],
            ["sy_fabian_hale", 1],
            ["sy_ignatius_hale", 1],
            ["sy_cleric_flaming_rose", 1],
            ["sy_eternal_fire_disciple", 2],
            ["sy_lonely_champion", 1],
            ["sy_inquisitor_helveed", 1]
        ]
    },
{
        "title": "Syndicate",
        "description": "Syndicate deck focusing on cards of the Eternal Fire - Playstyle: Witch Hunt, Muster, Dimeritium",
        "leader": "sy_gudrun_bjornsdottir",
        "faction": "syndicate",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 2],
            ["spe_rain", 1],
            ["spe_clear", 1],
            ["spe_dimeritium_shackles", 2],
            ["sy_flaming_rose_footman", 1],
            ["sy_witch_hunter", 1],
            ["sy_witch_hunter_executioner", 1],
            ["sy_eternal_fire_inquisitor", 1],
            ["sy_caleb_menge", 1],
            ["sy_moreelse", 1],
            ["sy_jacques_aldersberg", 1],
            ["sy_temple_guard", 1],
            ["sy_roderick_wett", 1],
            ["sy_ulrich", 1],
            ["ntr_triss", 1],
            ["ntr_geralt", 1],
            ["sy_walter_veritas", 1],
            ["sy_eternal_fire_priest_1", 1],
            ["sy_eternal_fire_priest_2", 1],
            ["sy_eternal_fire_priest_3", 1],
            ["sy_octavia_hale", 1],
            ["sy_fabian_hale", 1],
            ["sy_ignatius_hale", 1],
            ["sy_cleric_flaming_rose", 1],
            ["sy_eternal_fire_disciple", 2],
            ["sy_lonely_champion", 1],
            ["sy_inquisitor_helveed", 1]
        ]
    },
{
        "title": "Syndicate",
        "description": "Syndicate deck focusing on cards of the Eternal Fire - Playstyle: Witch Hunt, Muster, Dimeritium",
        "leader": "sy_cyprian_wiley",
        "faction": "syndicate",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 2],
            ["spe_rain", 1],
            ["spe_clear", 1],
            ["ntr_geralt", 1],
            ["ntr_triss", 1],
            ["ntr_ciri", 1],
            ["spe_dimeritium_shackles", 2],
            ["sy_flaming_rose_footman", 1],
            ["sy_witch_hunter", 1],
            ["sy_witch_hunter_executioner", 1],
            ["sy_eternal_fire_inquisitor", 1],
            ["sy_caleb_menge", 1],
            ["sy_moreelse", 1],
            ["sy_jacques_aldersberg", 1],
            ["sy_temple_guard", 1],
            ["sy_roderick_wett", 1],
            ["sy_ulrich", 1],
            ["sy_walter_veritas", 1],
            ["sy_eternal_fire_priest_1", 1],
            ["sy_eternal_fire_priest_2", 1],
            ["sy_eternal_fire_priest_3", 1],
            ["sy_octavia_hale", 1],
            ["sy_fabian_hale", 1],
            ["sy_ignatius_hale", 1],
            ["sy_cleric_flaming_rose", 1],
            ["sy_eternal_fire_disciple", 2],
            ["sy_lonely_champion", 1],
            ["sy_inquisitor_helveed", 1]
        ]
    },
  {
        "title": "Zerrikania",
        "description": "Zerrikania deck focusing on dragons and their whorshippers - Playstyle: Worshipper / Whorshipped",
        "leader": "ze_zerrikanterment",
        "faction": "zerrikania",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 2],
            ["spe_dragon_wrath", 1],
            ["spe_tse_tse_flies", 1],
            ["spe_clear", 1],
            ["spe_scorch", 1],
            ["ze_villentretenmerth", 1],
            ["ze_myrgtabrakke", 1],
            ["ze_merineaevelth", 1],
            ["ze_ocvist", 1],
            ["ze_keltullis", 1],
            ["ze_ostreverg", 1],
            ["ze_germinus", 1],
            ["ze_first_faithel_kia", 1],
            ["ze_tea_vea_1", 1],
            ["ze_tea_vea_2", 1],
            ["ze_faithel_1", 1],
            ["ze_faithel_2", 1],
            ["ze_faithel_3", 1],
            ["ze_balladeer", 1],
            ["ntr_geralt", 1],
            ["ze_tiger_1", 1],
            ["ze_tiger_2", 1],
            ["ze_yellow_witch_korath", 1],
            ["ze_emetouka", 1],
            ["ze_dragon_priestess_lua", 1],
            ["ze_high_priestess_nia", 1],
            ["ze_apucunpture_healer", 1],
            ["ze_collective_trance", 1],
        ]
    },
 {
        "title": "Zerrikania",
        "description": "Zerrikania deck focusing on dragons and their whorshippers - Playstyle: Worshipper / Whorshipped",
        "leader": "ze_baal_zebuth",
        "faction": "zerrikania",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 2],
            ["spe_dragon_wrath", 1],
            ["spe_tse_tse_flies", 1],
            ["spe_clear", 1],
            ["spe_scorch", 1],
            ["ntr_geralt", 1],
            ["ze_villentretenmerth", 1],
            ["ze_myrgtabrakke", 1],
            ["ze_merineaevelth", 1],
            ["ze_ocvist", 1],
            ["ze_keltullis", 1],
            ["ze_ostreverg", 1],
            ["ze_germinus", 1],
            ["ze_first_faithel_kia", 1],
            ["ze_tea_vea_1", 1],
            ["ze_tea_vea_2", 1],
            ["ze_faithel_1", 1],
            ["ze_faithel_2", 1],
            ["ze_faithel_3", 1],
            ["ze_balladeer", 1],
            ["ze_tiger_1", 1],
            ["ze_tiger_2", 1],
            ["ze_yellow_witch_korath", 1],
            ["ze_emetouka", 1],
            ["ze_dragon_priestess_lua", 1],
            ["ze_high_priestess_nia", 1],
            ["ze_apucunpture_healer", 1],
            ["ze_collective_trance", 1],
        ]
    },
{
        "title": "Zerrikania",
        "description": "Zerrikania deck focusing on dragons and their whorshippers - Playstyle: Worshipper / Whorshipped",
        "leader": "ze_rarog",
        "faction": "zerrikania",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 2],
            ["spe_dragon_wrath", 1],
            ["spe_tse_tse_flies", 1],
            ["spe_clear", 1],
            ["ntr_geralt", 1],
            ["spe_scorch", 1],
            ["ze_villentretenmerth", 1],
            ["ze_myrgtabrakke", 1],
            ["ze_merineaevelth", 1],
            ["ntr_triss", 1],
            ["ntr_ciri", 1],
            ["ze_ocvist", 1],
            ["ze_keltullis", 1],
            ["ze_ostreverg", 1],
            ["ze_germinus", 1],
            ["ze_first_faithel_kia", 1],
            ["ze_tea_vea_1", 1],
            ["ze_tea_vea_2", 1],
            ["ze_faithel_1", 1],
            ["ze_faithel_2", 1],
            ["ze_faithel_3", 1],
            ["ze_balladeer", 1],
            ["ze_tiger_1", 1],
            ["ze_tiger_2", 1],
            ["ze_yellow_witch_korath", 1],
            ["ze_emetouka", 1],
            ["ze_dragon_priestess_lua", 1],
            ["ze_high_priestess_nia", 1],
            ["ze_apucunpture_healer", 1],
            ["ze_collective_trance", 1],
        ]
    },
    {
        "title": "Velen",
        "description": "Deck relying mostly on bond, scorch and drawing cards",
        "leader": "ve_ghost_tree",
        "faction": "velen",
        "cards": [
            ["spe_horn", 1],
            ["spe_curse", 3],
            ["spe_decoy", 2],
            ["spe_scorch", 1],
            ["spe_clear", 1],
            ["ve_bloody_baron", 1],
            ["ntr_geralt", 1],
            ["ve_johnny", 1],
            ["ve_fugas", 1],
            ["ve_pellar", 1],
            ["ve_anna_strenger", 1],
            ["ve_fiend", 1],
            ["ve_chort", 1],
            ["ntr_vesemir", 1],
            ["ve_thecla", 1],
            ["ve_deserter_1", 1],
            ["ve_deserter_2", 1],
            ["ve_ghoul_1", 1],
            ["ve_ghoul_2", 1],
            ["ve_marauder_1", 1],
            ["ve_marauder_2", 1],
            ["ve_tamara_strenger", 1],
            ["ve_angry_peasants", 1],
            ["ve_hungry_wolves_4", 1],
            ["ve_hungry_wolves_1", 1],
            ["ve_hungry_wolves_2", 1],
            ["ve_hungry_wolves_3", 1],
            ["ve_abandoned_girl", 1]
        ]
    },
  {
        "title": "Velen",
        "description": "Deck relying mostly on bond, scorch and drawing cards",
        "leader": "ve_lady_wood_whispess",
        "faction": "velen",
        "cards": [
            ["spe_horn", 1],
            ["spe_curse", 3],
            ["spe_decoy", 2],
            ["spe_scorch", 1],
            ["spe_clear", 1],
            ["ve_bloody_baron", 1],
            ["ntr_geralt", 1],
            ["ve_johnny", 1],
            ["ve_fugas", 1],
            ["ve_pellar", 1],
            ["ve_anna_strenger", 1],
            ["ve_fiend", 1],
            ["ve_chort", 1],
            ["ntr_vesemir", 1],
            ["ve_thecla", 1],
            ["ve_deserter_1", 1],
            ["ve_deserter_2", 1],
            ["ve_ghoul_1", 1],
            ["ve_ghoul_2", 1],
            ["ve_marauder_1", 1],
            ["ve_marauder_2", 1],
            ["ve_tamara_strenger", 1],
            ["ve_angry_peasants", 1],
            ["ve_hungry_wolves_4", 1],
            ["ve_hungry_wolves_1", 1],
            ["ve_hungry_wolves_2", 1],
            ["ve_hungry_wolves_3", 1],
            ["ve_abandoned_girl", 1]
        ]
    },
  {
        "title": "Velen",
        "description": "Deck relying mostly on bond, scorch and drawing cards",
        "leader": "ve_lady_wood_brewess",
        "faction": "velen",
        "cards": [
            ["spe_horn", 1],
            ["spe_curse", 3],
            ["spe_decoy", 2],
            ["spe_scorch", 1],
            ["spe_clear", 1],
            ["ve_bloody_baron", 1],
            ["ntr_geralt", 1],
            ["ve_johnny", 1],
            ["ve_fugas", 1],
            ["ve_pellar", 1],
            ["ve_anna_strenger", 1],
            ["ve_fiend", 1],
            ["ve_chort", 1],
            ["ntr_vesemir", 1],
            ["ve_thecla", 1],
            ["ve_deserter_1", 1],
            ["ve_deserter_2", 1],
            ["ve_ghoul_1", 1],
            ["ve_ghoul_2", 1],
            ["ve_marauder_1", 1],
            ["ve_marauder_2", 1],
            ["ve_tamara_strenger", 1],
            ["ve_angry_peasants", 1],
            ["ve_hungry_wolves_4", 1],
            ["ve_hungry_wolves_1", 1],
            ["ve_hungry_wolves_2", 1],
            ["ve_hungry_wolves_3", 1],
            ["ve_abandoned_girl", 1]
        ]
    },
  {
        "title": "Velen",
        "description": "Deck relying mostly on bond, scorch and drawing cards",
        "leader": "ve_lady_wood_weavess",
        "faction": "velen",
        "cards": [
            ["spe_horn", 1],
            ["spe_curse", 3],
            ["spe_decoy", 2],
            ["spe_scorch", 1],
            ["spe_clear", 1],
            ["ve_bloody_baron", 1],
            ["ntr_geralt", 1],
            ["ve_johnny", 1],
            ["ve_fugas", 1],
            ["ve_pellar", 1],
            ["ve_anna_strenger", 1],
            ["ve_fiend", 1],
            ["ve_chort", 1],
            ["ntr_vesemir", 1],
            ["ve_thecla", 1],
            ["ve_deserter_1", 1],
            ["ve_deserter_2", 1],
            ["ve_ghoul_1", 1],
            ["ve_ghoul_2", 1],
            ["ve_marauder_1", 1],
            ["ve_marauder_2", 1],
            ["ve_tamara_strenger", 1],
            ["ve_angry_peasants", 1],
            ["ve_hungry_wolves_4", 1],
            ["ve_hungry_wolves_1", 1],
            ["ve_hungry_wolves_2", 1],
            ["ve_hungry_wolves_3", 1],
            ["ve_abandoned_girl", 1]
        ]
    },
 {
        "title": "Wild Hunt",
        "description": "Deck relying mostly on bond door mechanic",
        "leader": "wh_eredin_commander",
        "faction": "wild_hunt",
        "cards": [            
            ["ntr_geralt", 1],
            ["wh_imlerith", 1],
            ["wh_nithral", 1],
            ["wh_avallach", 1],
            ["wh_geels", 1],
            ["wh_navigator_3", 1],
            ["wh_wild_hunt_rider_1", 2],
            ["wh_wild_hunt_hound_1", 1],
            ["wh_wild_hunt_hound_2", 1],
            ["wh_wild_hunt_rider_3", 2],
            ["ntr_yennefer", 1],
            ["wh_naglfar_cartographer", 1],
            ["wh_naglfar_taskmaster", 1],
            ["wh_navigator_2", 1],
            ["wh_naglfar_crew", 2],
            ["wh_navigator_1", 1],
            ["wh_cirilla", 1],
            ["wh_aen_elle_conqueror_1", 1],
            ["ntr_mysterious_elf", 1]
        ]
    },
 {
        "title": "Wild Hunt",
        "description": "Deck relying mostly on bond door mechanic",
        "leader": "wh_imlerith_general",
        "faction": "wild_hunt",
        "cards": [            
            ["ntr_geralt", 1],
            ["wh_imlerith", 1],
            ["wh_nithral", 1],
            ["wh_avallach", 1],
            ["wh_geels", 1],
            ["wh_navigator_3", 1],
            ["wh_wild_hunt_rider_1", 2],
            ["wh_wild_hunt_hound_1", 1],
            ["wh_wild_hunt_hound_2", 1],
            ["wh_wild_hunt_rider_3", 2],
            ["ntr_yennefer", 1],
            ["wh_naglfar_cartographer", 1],
            ["wh_naglfar_taskmaster", 1],
            ["wh_navigator_2", 1],
            ["wh_naglfar_crew", 2],
            ["wh_navigator_1", 1],
            ["wh_cirilla", 1],
            ["wh_aen_elle_conqueror_1", 1],
            ["ntr_mysterious_elf", 1]
        ]
    },
    {
        "title": "Wild Hunt",
        "description": "Deck relying mostly on bond door mechanic",
        "leader": "wh_caranthir_navigator",
        "faction": "wild_hunt",
        "cards": [            
            ["ntr_geralt", 1],
            ["wh_imlerith", 1],
            ["wh_nithral", 1],
            ["wh_avallach", 1],
            ["wh_geels", 1],
            ["wh_navigator_3", 1],
            ["wh_wild_hunt_rider_1", 2],
            ["wh_wild_hunt_hound_1", 1],
            ["wh_wild_hunt_hound_2", 1],
            ["wh_wild_hunt_rider_3", 2],
            ["ntr_yennefer", 1],
            ["wh_naglfar_cartographer", 1],
            ["wh_naglfar_taskmaster", 1],
            ["wh_navigator_2", 1],
            ["wh_naglfar_crew", 2],
            ["wh_navigator_1", 1],
            ["wh_cirilla", 1],
            ["wh_aen_elle_conqueror_1", 1],
            ["ntr_mysterious_elf", 1]
        ]
    },
 {
        "title": "Wild Hunt",
        "description": "Deck relying mostly on bond door mechanic",
        "leader": "wh_winter_queen",
        "faction": "wild_hunt",
        "cards": [
            ["spe_decoy", 2],
            ["spe_scorch", 1],
            ["spe_clear", 1],
            ["spe_white_frost_1", 1],
            ["ntr_geralt", 1],
            ["wh_imlerith", 1],
            ["wh_nithral", 1],
            ["wh_avallach", 1],
            ["wh_geels", 1],
            ["wh_navigator_3", 1],
            ["wh_wild_hunt_rider_1", 2],
            ["wh_wild_hunt_rider_2", 2],
            ["wh_wild_hunt_hound_1", 1],
            ["ntr_yennefer", 1],
            ["wh_naglfar_cartographer", 1],
            ["wh_naglfar_taskmaster", 1],
            ["wh_navigator_2", 1],
            ["wh_wild_hunt_hound_2", 1],
            ["wh_navigator_1", 1],
            ["wh_nithral", 1],
            ["wh_cirilla", 1],
            ["ntr_ciri", 1],
            ["ntr_mysterious_elf", 1]
        ]
    },
	{
		"title": "Ofir",
		"description": "Nibras deck",
		"leader": "ofir_nibras",
		"faction": "ofir",
		"cards": [
			["spe_ofir_horn", 1],
			["spe_decoy", 1],
			["spe_clear", 1],
			["spe_ofir_sandstorm", 1],
                        ["ofir_chernobog", 1],
			["ofir_veles", 1],
			["ofir_devana", 1],
			["ofir_zoria", 1],
			["ofir_triglav", 1],
			["ntr_geralt", 1],
                        ["ofir_ofieri_prince", 1],
                        ["ofir_cavalry", 1],
                        ["ofir_radeyah", 1],
                        ["ofir_runewright", 1],
                        ["ntr_yennefer", 1],
                        ["ofir_zaira", 1],
                        ["ofir_cataphract_1", 1],
                        ["ofir_dulla", 1],
                        ["ofir_envoy_1", 1],
                        ["ofir_ofieri_mage", 1],
                        ["ofir_djinn1", 1],
                        ["ofir_ifrit_2", 1],
                        ["ofir_ifrit_3", 1],
                        ["ofir_sunsetwanderers", 1],
                        ["ofir_archmage_2", 1],
                        ["ofir_caravan_guard", 2],
                        ["ofir_desert_serpent", 1],
                        ["ofir_assassin", 1],
                        ["ofir_merchant", 1],
                        ["ofir_warrior_1", 1],
                        ["ofir_warrior_2", 1],
                        ["ofir_vanguard", 2],
                        ["ofir_aamads_guard_1", 1],
                        ["ofir_aamads_guard_2", 2],
                        ["ntr_dandelion", 1],
                        ["ofir_fathaa", 1]
		]
	},
{
		"title": "Ofir",
		"description": "Focus on sandstorms and overcoming elements",
		"leader": "ofir_nibras_gale",
		"faction": "ofir",
		"cards": [
			["spe_ofir_horn", 2],
			["spe_decoy", 1],
			["spe_clear", 1],
			["spe_ofir_sandstorm", 1],
                        ["ofir_morana", 1],
			["ofir_veles", 1],
			["ofir_perun", 1],
			["ofir_stribog", 1],
			["ntr_geralt", 1],
                        ["ofir_ofieri_prince", 1],
                        ["ofir_cavalry", 1],
                        ["ofir_radeyah", 1],
                        ["ofir_runewright", 1],
			["ntr_triss", 1],
                        ["ofir_zaira", 1],
                        ["ofir_cataphract_1", 1],
                        ["ofir_cataphract_2", 1],
                        ["ofir_cataphract_3", 1],
			["ofir_matta", 1],			
                        ["ofir_ofieri_mage", 1],
                        ["ofir_desert_banshee", 1],
                        ["ofir_djinn1", 1],
                        ["ofir_djinn2", 1],
                        ["ofir_djinn3", 1],
                        ["ofir_ifrit_2", 1],
                        ["ofir_sunsetwanderers", 1],
                        ["ofir_traveling_merchant", 1],
                        ["ofir_archmage_1", 1],
                        ["ofir_caravan_guard", 2],
                        ["ofir_desert_serpent", 1],
                        ["ofir_assassin", 1],
                        ["ofir_merchant", 1],
                        ["ofir_king_cobra", 1],
                        ["ofir_aamads_guard_1", 1],
                        ["ofir_aamads_guard_2", 1],
                        ["ntr_dandelion", 1],
                        ["ofir_saer_quan", 1],
                        ["ofir_fathaa", 1]
		]
	},
{
		"title": "Ofir",
		"description": "Focus on trade and adaptive abilities",
		"leader": "ofir_aamad_wise",
		"faction": "ofir",
		"cards": [
			["spe_ofir_horn", 2],
			["spe_decoy", 1],
			["spe_clear", 1],
			["spe_ofir_sandstorm", 1],
                        ["ofir_morana", 1],
			["ofir_svarog", 1],
			["ofir_perun", 1],
			["ofir_dazhbog", 1],
			["ofir_triglav", 1],
			["ntr_geralt", 1],
                        ["ofir_ofieri_prince", 1],
                        ["ofir_envoy_1", 1],
                        ["ofir_envoy_2", 1],
                        ["ofir_envoy_3", 1],
                        ["ofir_cavalry", 1],
                        ["ofir_radeyah", 1],
                        ["ofir_runewright", 1],
			["ntr_triss", 1],
                        ["ofir_zaira", 1],
                        ["ofir_cataphract_1", 1],
                        ["ofir_cataphract_2", 1],
			["ofir_matta", 1],			
                        ["ofir_ofieri_mage", 1],
                        ["ofir_desert_banshee", 1],
                        ["ofir_djinn1", 1],
                        ["ofir_djinn2", 1],
                        ["ofir_djinn3", 1],
                        ["ofir_ifrit_2", 1],
                        ["ofir_archmage_1", 1],
                        ["ofir_archmage_2", 1],
                        ["ofir_caravan_guard", 2],
                        ["ofir_desert_serpent", 1],
                        ["ofir_assassin", 1],
                        ["ofir_merchant", 1],
                        ["ofir_king_cobra", 1],
                        ["ofir_aamads_guard_1", 1],
                        ["ofir_aamads_guard_2", 2],
                        ["ofir_fortuneteller", 1],
                        ["ofir_saer_quan", 1],
                        ["ofir_fathaa", 1]
		]
	},
{
		"title": "Ofir",
		"description": "",
		"leader": "ofir_aamad",
		"faction": "ofir",
		"cards": [
			["spe_ofir_horn", 1],
			["ofir_stribog", 1],
			["spe_clear", 1],
			["spe_ofir_sandstorm", 1],
                        ["ofir_morana", 1],
			["ofir_svarog", 1],
			["ofir_perun", 1],
			["ofir_dazhbog", 1],
			["ofir_triglav", 1],
			["ntr_geralt", 1],
                        ["ofir_ofieri_prince", 1],
                        ["ofir_envoy_1", 1],
                        ["ofir_warrior_2", 1],
                        ["ntr_ciri", 1],
                        ["ofir_cavalry", 1],
                        ["ofir_radeyah", 1],
                        ["ofir_runewright", 1],
			["ntr_triss", 1],
                        ["ofir_zaira", 1],
                        ["ofir_cataphract_1", 1],
                        ["ofir_cataphract_2", 1],
			["ofir_matta", 1],			
                        ["ofir_ofieri_mage", 1],
                        ["ntr_yennefer", 1],
                        ["ofir_djinn1", 1],
                        ["ofir_rider_2", 1],
                        ["ofir_djinn3", 1],
                        ["ofir_ifrit_2", 1],
                        ["ofir_archmage_1", 1],
                        ["ofir_archmage_2", 1],
                        ["ofir_caravan_guard", 2],
                        ["ofir_desert_serpent", 1],
                        ["ofir_assassin", 1],
                        ["ofir_merchant", 1],
                        ["ofir_warrior_1", 1],
                        ["ofir_aamads_guard_1", 1],
                        ["ofir_aamads_guard_2", 2],
                        ["ntr_mysterious_elf", 1],
                        ["ofir_rider_1", 1]
		]
	},
{
		"title": "Free City of Novigrad",
		"description": "Free City of Novigrad",
		"leader": "nv_sigismund",
		"faction": "novigrad",
		"cards": [
			["nv_kalkstein", 1],
			["spe_decoy", 1],
			["nv_novigrad", 1],
			["ntr_geralt", 1],
			["spe_frost", 2],
			["nv_catanddog", 1],
			["nv_corinne", 1],
			["ntr_yennefer", 1],
			["ntr_dandelion", 1],
			["spe_cull", 2],
			["spe_clear", 1],
                        ["nv_field_marshal_duda", 1],
			["nv_dijkstra", 1],
			["nv_philippa", 1],
			["ntr_triss", 1],
			["nv_zoltan", 1],
			["ntr_ciri", 1],
                        ["spe_rain", 1],
                        ["nv_sarah", 1],
			["nv_doppler", 1],
			["nv_iris", 1],
			["nv_salma", 1],
			["nv_marquise_serenity", 1],
			["nv_passiflora_1", 1],
			["nv_hubert_rejk", 1],
			["nv_passiflora_3", 1],
			["nv_priscilla", 1],
			["nv_aphotecary", 1],
			["nv_eibhear_hattori", 1],
			["nv_imke", 1],
			["nv_ferko", 1],
			["spe_horn", 2],
			["spe_scorch", 1],
			["nv_dudu_biberveldt", 1],
		]
	},
{
		"title": "Free City of Novigrad",
		"description": "Free City of Novigrad",
		"leader": "nv_sigismund2",
		"faction": "novigrad",
		"cards": [
			["nv_kalkstein", 1],
			["spe_fog", 1],
			["spe_horn", 2],
			["nv_novigrad", 1],
			["ntr_geralt", 1],
			["spe_frost", 2],
			["nv_catanddog", 1],
			["nv_corinne", 1],
			["nv_dudu_biberveldt", 1],
			["ntr_yennefer", 1],
			["ntr_dandelion", 1],
			["spe_cull", 2],
			["spe_clear", 1],
                        ["nv_field_marshal_duda", 1],
			["nv_dijkstra", 1],
			["nv_philippa", 1],
			["nv_doppler", 1],
			["ntr_triss", 1],
			["nv_zoltan", 1],
			["ntr_ciri", 1],
                        ["spe_rain", 1],
                        ["nv_sarah", 1],
			["nv_iris", 1],
			["nv_salma", 1],
			["nv_hubert_rejk", 1],
			["nv_marquise_serenity", 1],
			["nv_passiflora_1", 1],
			["nv_passiflora_2", 1],
			["nv_passiflora_3", 1],
			["nv_priscilla", 1],
			["nv_ferko", 1],
			["nv_margarita", 1],
			["nv_eibhear_hattori", 1],
			["nv_imke", 1],
			["nv_renegade_mage", 1],
		]
	},
{
		"title": "Free City of Novigrad",
		"description": "Free City of Novigrad",
		"leader": "nv_cyrus_hemmelfart",
		"faction": "novigrad",
		"cards": [
			["nv_cantarella", 1],
			["spe_decoy", 1],
			["nv_novigrad", 1],
			["ntr_geralt", 1],
			["spe_fog", 2],
			["spe_horn", 2],
			["nv_catanddog", 1],
			["nv_corinne", 1],
			["ntr_yennefer", 1],
			["ntr_dandelion", 1],
			["spe_cull", 2],
			["spe_clear", 2],
                        ["nv_field_marshal_duda", 1],
			["nv_dudu_biberveldt", 1],
			["nv_doppler", 1],
			["nv_philippa", 1],
			["nv_iris", 1],
			["nv_hubert_rejk", 1],
			["nv_salma", 1],
			["nv_marquise_serenity", 1],
			["nv_passiflora_1", 1],
			["nv_passiflora_2", 1],
			["nv_passiflora_3", 1],
			["nv_priscilla", 1],
			["nv_imke", 1],
			["nv_eibhear_hattori", 1],
			["nv_margarita", 1],
			["nv_hubert_rejk", 1],
			["nv_ferko", 1],
			["nv_zoltan", 1],
			["nv_sarah", 1],
			["nv_kalkstein", 1],
			["ntr_triss", 1],
			["nv_aphotecary", 1],
			["nv_caesar_bilzen", 1],
		]
	}
];

/*
 * 
 */

var premade_deck = default_decks;
//premade_deck = custom_decks.concat(premade_deck);
//premade_deck = custom_decks;

var deckWeightConsts = {
    "spyBase": 20,
    "heroMult": 2,
    "musterMult": 2,
    "tightBondMult": 2,
    "medic": 7,
    "scorch": 5,
    "scorch_c": 5,
    "morale": 5,
    "agile": 2,
    "horn": 10,
    "berserker": 5,
    "mardroeme": 5,
    "avenger": 5,
    "decoy": 7,
    "clearWeatherWeight": 7,
    "heroSpyBase": 5,
    "cintra_slaughter": 5,
    "resilience": 5,
    "witcherSchoolWeight": 1,
    "witch_hunt": 5,
    "whorshipper": 2,
    "whorshipped": 2,
    "inspire": 3,
    "comrade": 7,
    "cull": 5,
    "emissary": 5
};

function calcDeckWeight(deck) {
    var total = 0;
    deck.cards.forEach(entry => {
        let c = card_dict[entry[0]];
        let cnt = parseInt(entry[1]);
        let abi = c["ability"].split(" ");
        let cStr = 0;
        if (!c["deck"].startsWith("special") && !c["deck"].startsWith("weather")) {
            if (abi.includes("spy")) {
                cStr = deckWeightConsts["spyBase"] - parseInt(c["strength"]);
                if (abi.includes("hero"))
                    cStr += deckWeightConsts["heroSpyBase"];
                if (c.row === "agile")
                    cStr += deckWeightConsts["agile"];
            } else {
                cStr = parseInt(c["strength"]);
                if (abi.includes("hero"))
                    cStr *= deckWeightConsts["heroMult"];
                if (abi.includes("bond"))
                    cStr *= deckWeightConsts["tightBondMult"];
                if (abi.includes("muster"))
                    cStr *= deckWeightConsts["musterMult"];
                abi.forEach(a => {
                    if (a in deckWeightConsts)
                        cStr += deckWeightConsts[a];
                });
                if (abi.includes("witcher_wolf_school") || abi.includes("witcher_bear_school") || abi.includes("witcher_viper_school") || abi.includes("witcher_cat_school") || abi.includes("witcher_griffin_school"))
                    cStr += deckWeightConsts["witcherSchoolWeight"];
                if (c.row === "agile")
                    cStr += deckWeightConsts["agile"];
            }
        }
        total += (cStr * cnt);
    });
    return total;
}